"use client";
import { KnowledgePhotos } from "./knowledge-photos";
import { useLanguage } from "./preferences";
import { useEffect, useRef, useState } from "react";
import { BookOpen, CheckCircle2, Plus, Search, X } from "lucide-react";
import type { Knowledge, Job } from "../lib/model";
const templates=[{type:'product',title:'Products & pricing',hint:'Describe your products, current prices, sizes, and product links. Include the date prices were checked.'},{type:'policy',title:'Delivery & returns',hint:'Where do you deliver? What are your shipping fees, delivery estimates, return window, and exceptions?'},{type:'faq',title:'Frequently asked questions',hint:'Write a customer question followed by an accurate answer. Include opening hours and how to contact the store.'},{type:'instruction',title:'Voice & boundaries',hint:'Describe how your store speaks, preferred greetings, and when a person should take over.'}];
export function ChatKnowledge({brandId,items,jobs,api,refresh,onCreatePost}:{onCreatePost:(item:Knowledge)=>void;brandId:string;items:Knowledge[];jobs:Job[];api:(path:string,init?:RequestInit)=>Promise<Record<string,unknown>>;refresh:()=>Promise<void>}) {
 const {t, t:translate}=useLanguage();
 const [search,setSearch]=useState(''),[editing,setEditing]=useState<Partial<Knowledge>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const lock=useRef(false);
 const [importUrl,setImportUrl]=useState(""),[importJob,setImportJob]=useState("");
 const importResult=jobs.find(j=>j.id===importJob);
 const importing=jobs.some(j=>j.kind==="knowledge.import"&&["queued","processing"].includes(j.status));
 useEffect(()=>{if(!importing&&(!importJob||importResult))return;const timer=setInterval(()=>void refresh(),3000);return()=>clearInterval(timer);},[importing,importJob,importResult,refresh]);
 const knowledge=items.filter(k=>k.scope==='chat'),approved=knowledge.filter(k=>k.status==='approved');
 async function run(work:()=>Promise<void>,message:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();await refresh();setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Could not save knowledge');}finally{setBusy(false);lock.current=false;}}
 return <section className="chat-library"><header className="inbox-hero"><div><span className="eyebrow">{t("TEACH NABD ABOUT YOUR STORE")}</span><h1>{t("Good answers start here")}</h1><p>{t("A private library of the facts your reply assistant is allowed to use.")}</p></div><button className="primary" onClick={()=>setEditing({type:'faq',title:'',content:''})}><Plus size={16}/>{t("Add knowledge")}</button></header><div className="inbox-summary"><span><BookOpen size={15}/>{approved.length}{" "}{t("approved")}</span><span>{knowledge.length-approved.length}{" "}{t("awaiting review")}</span><span>{t("Also available when choosing knowledge for a post")}</span></div>
 <form className="panel website-import" onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await api(`/v1/brands/${brandId}/knowledge/import`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({url:importUrl})});setImportJob(String(result.jobId));},"Website import queued. Review the extracted facts before approving them.");}}><div><h2>{t("Import from your website")}</h2><p>{t("Turn a product, FAQ, or policy page into knowledge for your AI.")}</p></div><label>{t("Public page URL")}<input required type="url" dir="ltr" placeholder={t("https://your-store.com/policies")} value={importUrl} onChange={e=>setImportUrl(e.target.value)}/></label><button className="primary" disabled={busy||importing}>{importing?t("Importing…"):t("Import page")}</button>{importResult&&<p role="status">{importResult.status==="completed"?(importResult.result?.truncated?t("Imported the first 12,000 characters. Review the draft below."):t("Imported. Review and approve the new knowledge below.")):importResult.error_summary||t("Import is running in the background.")}</p>}</form><div className="knowledge-starters">{templates.map(t=><button key={t.type} onClick={()=>setEditing({type:t.type,title:t.title,content:''})}><span><BookOpen size={20}/><Plus size={15}/></span><strong>{translate(t.title)}</strong><p>{translate(t.hint)}</p></button>)}</div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{t(notice)}</p>}
 {editing&&<form className="panel knowledge-editor" key={editing.id??editing.type} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api(`/v1/brands/${brandId}/knowledge${editing.id?'/'+editing.id:''}`,{method:editing.id?'PATCH':'POST',body:JSON.stringify({scope:'chat',type:f.get('type'),title:f.get('title'),content:f.get('content'),source:f.get('source')||''})});setEditing(null);},'Saved as a draft. Check the facts, then approve this knowledge for AI replies.');}}><div className="panel-title"><h2>{editing.id?t("Edit knowledge"):t("Add store knowledge")}</h2><button type="button" className="icon-button" aria-label={t("Close knowledge editor")} onClick={()=>setEditing(null)}><X size={19}/></button></div><div className="form-grid"><label>{t("Title")}<input name="title" defaultValue={editing.title} required maxLength={200}/></label><label>{t("Category")}<select name="type" defaultValue={editing.type}>{templates.map(t=><option value={t.type} key={t.type}>{translate(t.title)}</option>)}</select></label><label className="span-two">{t("Approved facts or guidance")}<textarea dir="auto" name="content" rows={6} required maxLength={12000} defaultValue={editing.content} placeholder={translate(templates.find(t=>t.type===editing.type)?.hint??"")}/></label><label className="span-two">{t("Source URL (optional)")}<input name="source" type="url" defaultValue={editing.source??''} placeholder={t("https://your-store.example/policies")}/></label></div><p className="muted">{t("Use verified information. Editing an approved item requires approval again. Don’t add passwords or API keys.")}</p><button className="primary" disabled={busy}>{t("Save for review")}</button></form>}
 <label className="inbox-search library-search"><Search size={16}/><input aria-label={t("Search AI knowledge")} placeholder={t("Search your store knowledge…")} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="knowledge-grid">{knowledge.filter(k=>`${k.title} ${k.content}`.toLowerCase().includes(search.toLowerCase())).map(k=><article className="panel knowledge-card" key={k.id}><div className="panel-title"><small className="eyebrow">{t(k.type)}</small><span className={`badge ${k.status}`}>{k.status==='approved'?<CheckCircle2 size={13}/>:null}{t(k.status)}</span></div><h3>{k.title}</h3><p dir="auto">{k.content}</p><KnowledgePhotos item={k} brandId={brandId} api={api} refresh={refresh}/><div className="card-actions"><button type="button" className="secondary" disabled={k.status!=="approved"} title={k.status!=="approved"?t("Approve first"):undefined} onClick={()=>onCreatePost(k)}>{t("Create post")}</button>{k.status!=='approved'&&<button className="primary" disabled={busy} onClick={()=>void run(async()=>{await api(`/v1/brands/${brandId}/knowledge/${k.id}/approve`,{method:'POST'});},'Knowledge approved for future AI suggestions.')}>{t("Approve")}</button>}<button className="secondary" onClick={()=>setEditing(k)}>{t("Edit")}</button><button className="text-button" disabled={busy} onClick={()=>void run(async()=>{await api(`/v1/brands/${brandId}/knowledge/${k.id}/archive`,{method:'POST'});},'Archived. Future AI replies will not use this item.')}>{t("Archive")}</button></div></article>)}</div>{!knowledge.length&&<div className="panel inbox-empty"><BookOpen size={28}/><h2>{t("Start with the questions customers ask most")}</h2><p>{t("Add products, shipping, and returns information above. Nabd will ask for help when your library does not contain an answer.")}</p></div>}</section>;
}
